### ISSUE TITLE
ทดสอบความสนุกของเกมกับเพื่อน

### ISSUE THREAD

**Issue by Thanaschai** [SCiRB/Project-Scratch-Game-10#1]

**Comment by Punnawich02** [comment]
ตอนที่ลองเล่นมาเจอบัคนิดหน่อย คือ หลังจากที่เล่นจบทุกด่านแล้ว พอกดรันอีกครั้งแมพจะไม่ขึ้น และพอกดเล่นผ่านลิงค์ จะขึ้นแค่ตัวด่าน แต่พื้นหลังไม่ขึ้น ต้องกดเข้าไปในโค้ดถึงจะใช้ได้ เดี๋ยวเราจะแนบรูป bug ที่เกิดไปให้

**Comment by Punnawich02** [comment]
![first bug](https://user-images.githubusercontent.com/110965971/189977454-d132a88c-b54f-4d7f-9ad4-1a54018d6c7f.jpg)
บัค กดเล่นในหน้าลิงค์แล้วมันจะขึ้นแค่ด่าน

![Second bug](https://user-images.githubusercontent.com/110965971/189977595-8dd75f42-51db-42c4-892a-8f31862925b6.jpg)
ต้องกดเข้าไปที่ ดูภายใน ถึงจะเล่นได้ได้ปกติ

![Third bug](https://user-images.githubusercontent.com/110965971/189977714-df004203-0602-4f9f-a7a3-978bd70927f2.jpg)
บัคเล่นจบทุกด่านแล้วพอกดเริ่มใหม่แล้วแมพจะไม่ขึ้น

**Comment by SCiRB** [comment]
ตอนนี้บัคแก้เรียบร้อยแล้ว เหตุเกิดจากการที่ตอนกดบันทึก ไม่ได้บันทึกเมื่อ Level = 0 เลยเกิดปัญหาแรกขึ้น ในส่วนของปัญหาที่ 2 ซึ่งเกิดเมื่อกดเริ่มเล่นอีกครั้งนั้นเกิดจากการที่ในตัว Demo ใช้คำสั่งซ่อน Object ไว้ตอนจบแต่เมื่อโค้ดเริ่มไม่ได้มีโค้ดเพื่อให้ Object แสดงออกมา จึงหายไปโดยปริยาย
