### ISSUE TITLE
ระบบเกม

### ISSUE THREAD

**Issue by SCiRB** [SCiRB/Project-Scratch-Game-10#18]
ระบบ Physics
ระบบการนับ Score ก่อนที่จะดึงธงขึ้นได้
ระบบการนับด่านที่อยู่ปัจจุบัน

**Comment by SCiRB** [comment]
ระบบ Physics และ ระบบการนับ Score ก่อนที่จะดึงธงขึ้นได้ ทำเสร็จแล้ว

**Comment by Punnawich02** [comment]
https://scratch.mit.edu/projects/731464921
อันนี้เป็นหน้า Start Menu และเมนูด้านในเกมเบื้องต้น

**Comment by Thanaschai** [comment]
![AF7961D0-15B6-4560-894F-6F66812F8C84](https://user-images.githubusercontent.com/110957704/190079192-4e97885d-9179-4063-9669-a7d372d5e98e.jpeg)

**Comment by SCiRB** [comment]
ระบบเกมตอนนี้เสร็จสมบูรณ์แล้ว : หน้าตา UI ตอนเริ่มเกม, ระบบเสียงและระบบการ Pause+Restart เสร็จสมบูรณ์
https://scratch.mit.edu/projects/731889166/

**Comment by Punnawich02** [comment]
**เจอบัค**
**หน้าเมนู**
Pause menu
1.
![pause menu 1 bug](https://user-images.githubusercontent.com/110965971/191041450-529f95b8-b5eb-40db-bda5-997e1dc18142.jpg)
กดปุ่ม pause แล้วรอจนกรอบของเมนูขึ้นมาสุด แล้วกดที่รูปพื้นหลัง ทำให้กรอบมันเลื่อนลง แต่เมนนูยังไม่หายไป

2.
![pause menu 2 bug](https://user-images.githubusercontent.com/110965971/191042051-209bbd07-c025-4286-ab94-1d45991d3786.jpg)
ในหน้า pause menu ไม่มีปุ่ม Exit ออกไปที่หน้าหลัก

**Comment by Punnawich02** [comment]
**bug ด่านต่างๆ**

ด่าน 3

![stage 3-1 bug](https://user-images.githubusercontent.com/110965971/191043288-76882d42-0322-4604-8fbf-1292fbcedf8d.jpg)
![stage 3-2 bug](https://user-images.githubusercontent.com/110965971/191043573-ed62b078-1da9-4e44-9b2e-da66a449cfb2.jpg)
![stage 3-3 bug](https://user-images.githubusercontent.com/110965971/191043604-58729310-a367-4e87-9bdf-099c776352b4.jpg)

พบว่าตัวสไปรท์สามารถขึ้นไปเกาะอยู่บนพื้นหลังได้ (บริเวณของของฉาก)

ด่าน 4
![stage 4-1 bug](https://user-images.githubusercontent.com/110965971/191043836-2da0fb0f-918d-4a35-b9ff-bdf28215cae8.jpg)

เกิดบัคตามนี้ (น่าจะเกิดจากการที่ยังทำตัวเกมส์ไม่เสร็จ)

**Comment by Punnawich02** [comment]
จากที่ Test มา ตอนนี้บัคได้แก้หมดแล้วครับ

**Comment by Thanaschai** [comment]
![พุ่มไม้ 2](https://user-images.githubusercontent.com/110957704/191443587-ae3b8d90-11b5-49a3-b803-fed74c3eeb95.png)
