### ISSUE TITLE
CODE MERGING

### ISSUE THREAD

**Issue by Thanaschai** [SCiRB/Project-Scratch-Game-10#3]

**Comment by Thanaschai** [comment]
โค้ดที่สร้างแล้วสามารถอัพเดตได้ในนี้เลยนะครับ ระบุสิ่งที่เพิ่มมาในโค้ดด้วยนะ

**Comment by SCiRB** [comment]
ตัวละครกบเสร็จสมบูรณ์ มี Sprite Animation ที่ถูกต้อง มี Interaction กับสิ่งต่างๆอย่างปกติแล้ว

**Comment by SCiRB** [comment]
ทุกโค๊ดสามารถทำงานร่วมกันได้อย่างถูกต้องแล้ว
https://scratch.mit.edu/projects/729941866/
