### ISSUE TITLE
รูปแบบเกมเบื้องต้น

### ISSUE THREAD

**Issue by Thanaschai** [SCiRB/Project-Scratch-Game-10#5]
[BASICCOM.pdf](https://github.com/SCiRB/Project-Scratch-Game-10/files/9491600/BASICCOM.pdf)

**Comment by Thanaschai** [comment]
[BASICCOM 2.pdf](https://github.com/SCiRB/Project-Scratch-Game-10/files/9491606/BASICCOM.2.pdf)

**Comment by CHICKIINY** [comment]
[game.pdf](https://github.com/SCiRB/Project-Scratch-Game-10/files/9494740/game.pdf)

**Comment by CHICKIINY** [comment]
![Uploading 55.png…]()

**Comment by CHICKIINY** [comment]
![57](https://user-images.githubusercontent.com/110966137/188825733-1b7ab3c4-4cd5-4ad8-9773-4ac4fd087a0c.png)
![58](https://user-images.githubusercontent.com/110966137/188825738-9a99189c-1c60-4492-ad60-bc6668c4ae28.png)

**Comment by CHICKIINY** [comment]
![Uploading 55.png…]()

**Comment by CHICKIINY** [comment]
![56](https://user-images.githubusercontent.com/110966137/188825882-d6cd7e15-4baf-4d2b-a20c-861d600e2b72.png)
