### ISSUE TITLE
Design Characters

### ISSUE THREAD

**Issue by SCiRB** [SCiRB/Project-Scratch-Game-10#8]

**Comment by SCiRB** [comment]
Main Characters
-Player 1 (Chickiiny)
-Player 2 (Frog)
Objects
-Grade A
-Covid Virus
-Rains
-Fish
-Cannon
-Bullet

**Comment by CHICKIINY** [comment]
![ไม่มีชื่อ 7_20220518224446](https://user-images.githubusercontent.com/110966137/189947206-69868a98-1029-4ce3-93e7-366152d05641.png)

![ไม่มีชื่อ 38_20220609204948](https://user-images.githubusercontent.com/110966137/189947263-283de407-843e-44e4-9f62-6e52bb28a119.png)

**Comment by CHICKIINY** [comment]
![ไม่มีชื่อ 59_20220912214045](https://user-images.githubusercontent.com/110966137/189947441-cd186575-95b2-40ac-8f91-134b0f417dd1.png)
![ไม่มีชื่อ 60_20220913224748](https://user-images.githubusercontent.com/110966137/189947468-675a5aa0-0b7e-4e42-b90c-efa8f66b503d.png)

**Comment by CHICKIINY** [comment]
![ไม่มีชื่อ 66_20220913203841](https://user-images.githubusercontent.com/110966137/189947548-9ed25d80-1ed3-4281-b28d-b9bdee509ec2.png)
![IMG_0300](https://user-images.githubusercontent.com/110966137/189947739-50d90ae5-140c-4576-bc48-650f22e3b48f.png)

**Comment by CHICKIINY** [comment]
![IMG_0301](https://user-images.githubusercontent.com/110966137/189947812-a7815ae9
![IMG_0303](https://user-images.githubusercontent.com/110966137/189947905-c820e50d-b8a8-4d40-a289-f5204e22f42f.png)
-1014-4543-8775-2b3e874dfe09.png)

**Comment by CHICKIINY** [comment]
![IMG_0301](https://user-images.githubusercontent.com/110966137/189947978-2f11ab8e-5965-484a-9118-b0419b072520.png)
![IMG_0302](https://user-images.githubusercontent.com/110966137/189948030-43d7e889-1fbd-4d60-8c75-1528b4793825.png)
![IMG_0303](https://user-images.githubusercontent.com/110966137/189948056-4103f0db-6d93-41ff-af70-6498b101369f.png)

**Comment by CHICKIINY** [comment]
![ไม่มีชื่อ 65_20220913185447](https://user-images.githubusercontent.com/110966137/189948817-ccc8afe2-817b-48d6-8444-b0cd3eb88625.png)
![ไม่มีชื่อ 64_20220913183709](https://user-images.githubusercontent.com/110966137/189948847-1b146d6b-68c8-40d9-bd7b-47e32e5f63fd.png)

**Comment by SCiRB** [comment]
ทุกตัวละครออกแบบเสร็จแล้ว

**Comment by CHICKIINY** [comment]
![IMG_0305](https://user-images.githubusercontent.com/110966137/190076628-89c0c1c9-adf1-493a-b783-aebe5534291c.png)

**Comment by CHICKIINY** [comment]
![71](https://user-images.githubusercontent.com/110966137/190925859-1f94af6c-097b-4417-bd42-91bf2cd0cd88.png)
![72_20220918022923](https://user-images.githubusercontent.com/110966137/190925861-f4ec66af-8bb8-4cf3-a636-813aa584ae96.PNG)
