### ISSUE TITLE
Design Map

### ISSUE THREAD

**Issue by SCiRB** [SCiRB/Project-Scratch-Game-10#9]

**Comment by SCiRB** [comment]
Map Design
-Map 1 (Clock tower)
-Map 2 (Rainy Days)
-Map 3 (Angkaew)
-Map 4 (4 Floors Building)

**Comment by Punnawich02** [comment]
![4C6E01AC-0249-4B34-9188-4DCD51014B94](https://user-images.githubusercontent.com/110965971/189685793-4392e54c-5f2e-4d1e-b283-b9725129d654.jpeg)
อันนี้ไปลองๆคิดมา ว่าในแต่ละหน้าเมนูน่าจะมีอะไรมั่ง

**Comment by Punnawich02** [comment]
![Uploading D04B78EA-0A24-4D3B-84C0-6661D3C72E83.jpeg…]()

**Comment by Thanaschai** [comment]
![RiTTA2](https://user-images.githubusercontent.com/110957704/189728351-c488458f-b908-4d4f-be05-72b534bd70ae.jpg)

**Comment by Thanaschai** [comment]
![หอสามชาย](https://user-images.githubusercontent.com/110957704/189728425-0be3fe18-dc22-444e-bcd1-a381dfb55708.png)
![อาคาร 30 ปี](https://user-images.githubusercontent.com/110957704/189728434-772f35ef-31eb-4788-b2e0-f078f7f845d9.png)
![RB3](https://user-images.githubusercontent.com/110957704/189728440-3d0071cb-a57a-4fb3-aa0b-98cf9d1d34d6.png)
![RB5](https://user-images.githubusercontent.com/110957704/189728446-5028ce3f-d90f-4bb7-aff3-312ad0af346c.png)
![university](https://user-images.githubusercontent.com/110957704/189728448-3b65fc7c-aaf2-46a0-a27a-ae62f37a9575.png)
![เครื่องกล 1](https://user-images.githubusercontent.com/110957704/189728452-c21ed7a9-d709-4ca8-8741-58a09e1b5e8d.png)
![ตึก 30 ปี](https://user-images.githubusercontent.com/110957704/189728458-2f7df405-670a-4c75-970d-a594fd8e9d25.png)
![ตึก scb](https://user-images.githubusercontent.com/110957704/189728461-8ae4bef9-58a3-47ec-919c-18da109659f2.png)

**Comment by SCiRB** [comment]
Map สำหรับ Demo จะใช้แค่ Map 1 ก่อน ซึ่งเสร็จสมบูรณ์แล้ว
